# ============================================================================
# Title:   The SYNTH02 study specification
# Purpose: The second study - the proof that "a new study is a spec change".
#          Same CRF family as SYNTH01, different everything a real study
#          changes: sponsor and study ids, three European sites, four arms of
#          SYN-201, a schedule without Week 2 but with Week 12, a
#          straight-4-point causality decode, an extra discontinuation reason
#          (PHYSICIAN DECISION), a respiratory rate on the VS form, an AST
#          analyte in the lab panel, and a lot-number SUPP qualifier on EX.
#          No mapper, derivation or validator was changed to make this run.
# ============================================================================

#' The SYNTH02 study specification
#'
#' A second, deliberately different [study_spec][new_study_spec()] for the
#' synthetic study generated by [generate_rave_extract()] with
#' `study = "SYNTH02"`. It maps a different set of sites, arms, visits,
#' codelists, tests and SUPP
#' qualifiers through the same mappers as [spec_synth01] - run
#' `build_all(extract, spec = spec_synth02)` on the SYNTH02 extract and the
#' whole pipeline validates cleanly. Anything the two studies share is the
#' CRF family; anything that differs is a row in one of these tables.
#' The trial design tables follow the same rule: four arms x two elements,
#' two elements, six criteria and seven trial summary parameters, all
#' different from SYNTH01 without a mapper change.
#'
#' @format A `study_spec` object (a validated named list of tibbles).
#' @source Assembled from the SYNTH02 CRF design; see `?new_study_spec`
#'   for the table structure.
#' @export
spec_synth02 <- new_study_spec(
  study = tibble(
    STUDYID = "4033",
    PROJECT = "SYNTH02",
    seed    = 20260904,
    n       = 18L,
    # the protocol's adult population; validate_adam() checks AGE against it
    age_min = 18L,
    age_max = 100L
  ),

  sites = tribble(
    ~siteid, ~SiteNumber, ~Site,                                ~SiteGroup, ~StudySiteId, ~COUNTRY,
    "4201",  "201",       "Hopital Saint-Louis",                "Europe",   "8801",       "FRA",
    "4202",  "202",       "Hospital Universitari Vall d'Hebron", "Europe",  "8802",       "ESP",
    "4203",  "203",       "Guy's Hospital",                     "Europe",   "8803",       "GBR"
  ),

  arms = tribble(
    ~ARMCD_DECODE,    ~ARMCD,    ~ARM,
    "Placebo",        "PBO",     "Placebo",
    "SYN-201 25 mg",  "SYN25",   "SYN-201 25 mg",
    "SYN-201 50 mg",  "SYN50",   "SYN-201 50 mg",
    "SYN-201 100 mg", "SYN100",  "SYN-201 100 mg"
  ),

  visits = tribble(
    ~Folder, ~VISITNUM, ~VISIT,             ~EPOCH,      ~TargetDays,
    "SCRN",  1,         "SCREENING",        "SCREENING", -14L,
    "BASE",  2,         "BASELINE",         "TREATMENT", 0L,
    "WK04",  3,         "WEEK 4",           "TREATMENT", 28L,
    "WK08",  4,         "WEEK 8",           "TREATMENT", 56L,
    "WK12",  5,         "WEEK 12",          "TREATMENT", 84L,
    "EOT",   6,         "END OF TREATMENT", "TREATMENT", 112L
  ),

  # Trial design, SYNTH02 flavour: four arms of SYN-201 in COPD, a 16-week
  # treatment element (EOT sits at day 112), and its own criteria set.
  elements = tribble(
    ~ETCD,   ~ELEMENT,    ~TESTRL,                     ~TEENRL,                            ~TEDUR,
    "SCRN",  "Screening", "Informed consent obtained", "Randomised or screen failure",     "P2W",
    "TREAT", "Treatment", "First dose of study drug",  "End of treatment visit completed", "P16W"
  ),

  ta = tribble(
    ~ARMCD,   ~ETCD,   ~TAETORD, ~EPOCH,      ~TABRANCH,                        ~TATRANSAC,
    "PBO",    "SCRN",  1L,       "SCREENING", NA,                               "Randomised",
    "PBO",    "TREAT", 2L,       "TREATMENT", "Randomised to Placebo",          NA,
    "SYN25",  "SCRN",  1L,       "SCREENING", NA,                               "Randomised",
    "SYN25",  "TREAT", 2L,       "TREATMENT", "Randomised to SYN-201 25 mg",    NA,
    "SYN50",  "SCRN",  1L,       "SCREENING", NA,                               "Randomised",
    "SYN50",  "TREAT", 2L,       "TREATMENT", "Randomised to SYN-201 50 mg",    NA,
    "SYN100", "SCRN",  1L,       "SCREENING", NA,                               "Randomised",
    "SYN100", "TREAT", 2L,       "TREATMENT", "Randomised to SYN-201 100 mg",   NA
  ),

  ie = tribble(
    ~IETESTCD, ~IETEST,                                                                   ~IECAT,
    "INC1",    "Age 18 to 100 years, inclusive",                                          "INCLUSION",
    "INC2",    "Diagnosis of chronic obstructive pulmonary disease per protocol section 4.1", "INCLUSION",
    "INC3",    "Written informed consent obtained before any study procedure",            "INCLUSION",
    "EXC1",    "Treatment with an investigational drug within 30 days before screening",  "EXCLUSION",
    "EXC2",    "Pregnant or breastfeeding",                                               "EXCLUSION",
    "EXC3",    "Clinically significant laboratory abnormality at screening",              "EXCLUSION"
  ),

  ts = tribble(
    ~TSPARMCD, ~TSPARM,                              ~TSVAL,                                                                   ~TSVALNF,
    "TITLE",   "Trial Title",                        "A Phase II randomised, double-blind, placebo-controlled study of SYN-201", NA,
    "PHASE",   "Trial Phase Classification",         "PHASE II",                                                                NA,
    "SPONSOR", "Clinical Study Sponsor",             "SYNTH Pharmaceuticals",                                                   NA,
    "INDIC",   "Trial Indication",                   "Chronic Obstructive Pulmonary Disease",                                   NA,
    "TRT",     "Investigational Therapy or Treatment", "SYN-201; Placebo",                                                      NA,
    "NARMS",   "Planned Number of Arms",             "4",                                                                       NA,
    "PLANSUB", "Planned Number of Subjects",         "18",                                                                      NA
  ),

  codelists = tribble(
    ~ct,      ~rave_decode,                    ~cdisc_term,
    # AE outcome (AEOUT): same CDISC CT as SYNTH01
    "AEOUT",  "Recovered/Resolved",            "RECOVERED/RESOLVED",
    "AEOUT",  "Recovering/Resolving",          "RECOVERING/RESOLVING",
    "AEOUT",  "Not recovered/Not resolved",    "NOT RECOVERED/NOT RESOLVED",
    "AEOUT",  "Fatal",                         "FATAL",
    "AEOUT",  "Unknown",                       "UNKNOWN",
    # AE action taken (AEACN)
    "AEACN",  "Dose not changed",              "DOSE NOT CHANGED",
    "AEACN",  "Dose reduced",                  "DOSE REDUCED",
    "AEACN",  "Drug interrupted",              "DRUG INTERRUPTED",
    "AEACN",  "Drug withdrawn",                "DRUG WITHDRAWN",
    # AE severity (AESEV)
    "AESEV",  "Mild",                          "MILD",
    "AESEV",  "Moderate",                      "MODERATE",
    "AESEV",  "Severe",                        "SEVERE",
    # AE causality (AEREL): this sponsor keeps the collected 4-point scale
    # instead of SYNTH01's collapse to related / not related
    "AEREL",  "Not related",                   "NOT RELATED",
    "AEREL",  "Possibly related",              "POSSIBLY RELATED",
    "AEREL",  "Probably related",              "PROBABLY RELATED",
    "AEREL",  "Related",                       "RELATED",
    # Disposition reason (DSDECOD): this protocol adds PHYSICIAN DECISION
    "DSDECOD", "COMPLETED",                    "COMPLETED",
    "DSDECOD", "ADVERSE EVENT",                "ADVERSE EVENT",
    "DSDECOD", "WITHDRAWAL BY SUBJECT",        "WITHDRAWAL BY SUBJECT",
    "DSDECOD", "LOST TO FOLLOW-UP",            "LOST TO FOLLOW-UP",
    "DSDECOD", "PROTOCOL DEVIATION",           "PROTOCOL DEVIATION",
    "DSDECOD", "DEATH",                        "DEATH",
    "DSDECOD", "PHYSICIAN DECISION",           "PHYSICIAN DECISION",
    # Sex (SEX)
    "SEX",    "Male",                          "M",
    "SEX",    "Female",                        "F"
  ),

  supp = tribble(
    ~rdomain, ~idvar,   ~qnam,      ~qlabel,                              ~src,       ~transform, ~qorig, ~qeval,
    "DM",     NA,       "SUBJINIT", "Subject Initials",                   "SUBJINIT", "squish",   "CRF",  NA,
    "DM",     NA,       "CHILDPOT", "Childbearing Potential",             "CHILDPOT", "yn",       "CRF",  NA,
    "DM",     NA,       "RACEOTH",  "Race, Other Specify",                "RACEOTH",  "verbatim", "CRF",  NA,
    "AE",     "AESEQ",  "AESI",     "Adverse Event of Special Interest",  "AESI",     "yn",       "CRF",  "INVESTIGATOR",
    "AE",     "AESEQ",  "AEDISCON", "AE Led to Study Discontinuation",    "AEDISCON", "yn",       "CRF",  NA,
    "EX",     "EXSEQ",  "EXADMBY",  "Dose Administered By",               "EXADMBY",  "squish",   "CRF",  NA,
    # the study's extra non-standard field: the dose's lot number
    "EX",     "EXSEQ",  "EXLOT",    "Lot Number",                         "EXLOT",    "squish",   "CRF",  NA
  ),

  units = tribble(
    ~testcd,  ~conv_from, ~conv_to,  ~conv_factor,
    "GLUC",   "MG/DL",    "mmol/L",  1 / 18.0156,
    "CREAT",  "MG/DL",    "umol/L",  88.42,
    "HGB",    "G/DL",     "g/L",     10
  ),

  forms = tribble(
    ~form_oid, ~type,    ~scheduled,
    "DM",      "event",  TRUE,
    "VS",      "event",  TRUE,
    "EX",      "event",  TRUE,
    "DS",      "event",  TRUE,
    "LB",      "event",  TRUE,
    "AE",      "log",    FALSE,
    "CM",      "log",    FALSE,
    "MH",      "log",    FALSE
  ),

  tests = tribble(
    ~domain,  ~field,   ~testcd,  ~test,                        ~cat,         ~specimen,
    "VS",     "SYSBP",  "SYSBP",  "Systolic Blood Pressure",    NA,           NA,
    "VS",     "DIABP",  "DIABP",  "Diastolic Blood Pressure",   NA,           NA,
    "VS",     "PULSE",  "PULSE",  "Pulse Rate",                 NA,           NA,
    # this protocol adds a respiratory rate collection
    "VS",     "RESP",   "RESP",   "Respiration Rate",           NA,           NA,
    "VS",     "TEMP",   "TEMP",   "Temperature",                NA,           NA,
    "VS",     "WEIGHT", "WEIGHT", "Weight",                     NA,           NA,
    "VS",     "HEIGHT", "HEIGHT", "Height",                     NA,           NA,
    "LB",     "GLUC",   "GLUC",   "Glucose",                    "CHEMISTRY",  "SERUM",
    "LB",     "CREAT",  "CREAT",  "Creatinine",                 "CHEMISTRY",  "SERUM",
    "LB",     "HGB",    "HGB",    "Hemoglobin",                 "HEMATOLOGY", "BLOOD",
    "LB",     "POT",    "K",      "Potassium",                  "CHEMISTRY",  "SERUM",
    "LB",     "ALT",    "ALT",    "Alanine Aminotransferase",   "CHEMISTRY",  "SERUM",
    # and an AST analyte in the central lab panel
    "LB",     "AST",    "AST",    "Aspartate Aminotransferase", "CHEMISTRY",  "SERUM"
  ),

  bds = tribble(
    ~domain, ~paramcd, ~paramn, ~anrlo, ~anrhi,
    # ADVS: the SAP stand-in ranges, RESP included
    "ADVS", "SYSBP",  1,  90,   140,
    "ADVS", "DIABP",  2,  50,   90,
    "ADVS", "PULSE",  3,  50,   120,
    "ADVS", "RESP",   4,  12,   20,
    "ADVS", "TEMP",   5,  35,   37.5,
    "ADVS", "WEIGHT", 6,  NA,   NA,
    "ADVS", "HEIGHT", 7,  NA,   NA,
    # ADLB: ranges arrive with each record; AST joins the ordering
    "ADLB", "GLUC",   1,  NA,   NA,
    "ADLB", "CREAT",  2,  NA,   NA,
    "ADLB", "HGB",    3,  NA,   NA,
    "ADLB", "K",      4,  NA,   NA,
    "ADLB", "ALT",    5,  NA,   NA,
    "ADLB", "AST",    6,  NA,   NA
  ),

  # Same CRF family as SYNTH01, so the variable-level mapping carries over
  # unchanged: every crf_field, transform and derivation reference is
  # identical. The study differences above are the spec change.
  variables = spec_synth01$variables
)
